spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
    # create 모드: 실행마다 테이블이 재생성됨
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true  log가 system.out으로 출려됨
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug  # sql이 logger로 모두 나타남
    org.hibernate.type: trace
